//! Translator for the armv6-m instruction set

use armv6_m_instruction_parser::instructons::Instruction;

use crate::general_assembly::translator::Translator;

impl Translator for Instruction {
    fn translate(&self) -> crate::general_assembly::instruction::Instruction {
        match &self.operation {
            armv6_m_instruction_parser::instructons::Operation::ADCReg { m, n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ADDImm { imm, n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ADDReg { m, n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ADDImmSP { d, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ADDRegSP { d, m } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ADR { d, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ANDReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ASRImm { imm, m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ASRReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::B { cond, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::BICReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::BKPT { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::BL { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::BLXReg { m } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::BX { m } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::CMNReg { m, n } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::CMPImm { n, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::CMPReg { m, n } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::CPS { im } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::CPY => todo!(),
            armv6_m_instruction_parser::instructons::Operation::DMB { option } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::DSB { option } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::EORReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ISB { option } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDM { n, reg_list } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRLiteral { t, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRBImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRBReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRHImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRHReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRSBReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LDRSH { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LSLImm { imm, m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LSLReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LSRImm { imm, m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::LSRReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::MOVImm { d, imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::MOVReg { m, d, set_flags } => {
                todo!()
            }
            armv6_m_instruction_parser::instructons::Operation::MRS { d, sysm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::MSRReg { n, sysm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::MUL { n, dm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::MVNReg { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::NOP => todo!(),
            armv6_m_instruction_parser::instructons::Operation::ORRReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::POP { reg_list } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::PUSH { reg_list } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::REV { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::REV16 { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::REVSH { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::RORReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::RSBImm { n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SBCReg { m, dn } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SEV => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STM { n, reg_list } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRBImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRBReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRHImm { imm, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::STRHReg { m, n, t } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SUBImm { imm, n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SUBReg { m, n, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SUBImmSP { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SVC { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SXTB { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::SXTH { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::TSTReg { m, n } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::UDFT1 { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::UDFT2 { imm } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::UXTB { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::UXTH { m, d } => todo!(),
            armv6_m_instruction_parser::instructons::Operation::WFE => todo!(),
            armv6_m_instruction_parser::instructons::Operation::WFI => todo!(),
            armv6_m_instruction_parser::instructons::Operation::YIELD => todo!(),
        }
    }
}
